// app/layout.tsx or app/RootLayout.tsx
import { UserProvider } from "./context/UserContext"; // Adjust path as needed
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavBar } from "@/components/navbar";
import Footer from "@/components/footer";
import { getServerSession } from "next-auth"; // Import the session checker
import { authOptions } from "@/app/utils/auth"; // Adjust the import according to your project structure

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap the app with UserProvider so user data is accessible */}
        <UserProvider>
          {/* You can add NavBar, Footer, etc. here */}
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
