version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: registration # Change to 'registration' to match the application properties
    ports:
      - "3307:3306"
    networks:
      - agrialert-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agrialert
    ports:
      - "8087:8087"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/registration # Match the new database name
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - agrialert-network

networks:
  agrialert-network:
